const $=(s,ctx=document)=>ctx.querySelector(s);const $$=(s,ctx=document)=>[...ctx.querySelectorAll(s)];
const state={role:'jefe',page:'dashboard',kpis:JSON.parse(localStorage.getItem('gd-kpis')||'null')||[
{id:1,title:'Reducir tiempo de respuesta de solicitudes',meta:'24 horas',base:'48 horas',indicator:'Tiempo promedio de respuesta',progress:72},
{id:2,title:'Digitalizar expedientes administrativos',meta:'100%',base:'35%',indicator:'Porcentaje de expedientes digitalizados',progress:64}
],answers:JSON.parse(localStorage.getItem('gd-eval')||'{}')};
const questions=[
{title:'Cumplimiento de funciones y objetivos',text:'¿En qué medida has cumplido tus funciones y objetivos?',evidence:true,rubrics:{1:'No cumplí responsabilidades u objetivos clave del período.',2:'Cumplí parcialmente; tuve retrasos, omisiones o brechas relevantes.',3:'Cumplí lo principal, aunque pude hacerlo mejor en algunos aspectos.',4:'Cumplí de forma consistente y con resultados sólidos.',5:'Superé ampliamente lo esperado, asumí retos adicionales y generé un impacto excepcional comprobable.'}},
{title:'Calidad',text:'¿Cómo calificarías la calidad de tu trabajo?',evidence:true,rubrics:{1:'La calidad fue insuficiente de manera recurrente.',2:'Mi trabajo presentó errores o reprocesos frecuentes.',3:'Mi trabajo fue adecuado, aunque requirió ajustes o correcciones puntuales.',4:'Mi trabajo fue confiable, preciso y cumplió los estándares esperados.',5:'Entregué un trabajo excepcional, superior al estándar del rol y con valor agregado comprobable.'}},
{title:'Iniciativa',text:'¿Tomas la delantera al detectar oportunidades o desafíos, proponiendo soluciones concretas antes de que se conviertan en obstáculos?',rubrics:{1:'Nunca',2:'Ocasionalmente',3:'Regularmente',4:'Frecuentemente',5:'Siempre'}},
{title:'Mejora continua',text:'¿Implementas acciones concretas para mejorar las formas de trabajo existentes en la universidad o en tu área?',rubrics:{1:'Nunca',2:'Ocasionalmente',3:'Regularmente',4:'Frecuentemente',5:'Siempre'}}
];
function navigate(page){state.page=page;$$('.page').forEach(x=>x.classList.toggle('active-page',x.id===page));$$('.nav-link').forEach(x=>x.classList.toggle('active',x.dataset.page===page));window.scrollTo({top:0,behavior:'smooth'});}
$$('[data-page]').forEach(b=>b.addEventListener('click',()=>navigate(b.dataset.page)));
$('#menuBtn').addEventListener('click',()=>$('#sidebar').classList.toggle('collapsed'));
function applyRole(){const r=state.role;$$('.role-jefe,.role-admin,.role-comite').forEach(x=>x.style.display='none');if(r==='jefe')$$('.role-jefe').forEach(x=>x.style.display='');if(r==='admin')$$('.role-admin').forEach(x=>x.style.display='');if(r==='comite')$$('.role-comite').forEach(x=>x.style.display='');if(r==='admin')navigate('admin');else if(r==='comite')navigate('committee');else navigate('dashboard');}
$('#roleSelect').addEventListener('change',e=>{state.role=e.target.value;applyRole();toast('Vista cambiada a '+e.target.options[e.target.selectedIndex].text)});applyRole();
function renderKpis(){const c=$('#kpiList');c.innerHTML='';state.kpis.forEach(k=>{const el=document.createElement('article');el.className='panel kpi-card';el.innerHTML=`<div class="panel-heading"><div><h2>${k.title}</h2><p>${k.indicator}</p></div><span class="status-pill ${k.progress>=70?'success':'warning'}">${k.progress}% avance</span></div><div class="kpi-grid"><div><span class="kpi-value">Indicador<strong>${k.indicator}</strong></span></div><div><span class="kpi-value">Línea base<strong>${k.base}</strong></span></div><div><span class="kpi-value">Meta<strong>${k.meta}</strong></span></div></div><div style="margin-top:16px"><div class="goal-top"><span>Progreso registrado</span><strong>${k.progress}%</strong></div><input class="kpi-slider" data-id="${k.id}" type="range" min="0" max="100" value="${k.progress}" style="width:100%"></div>`;c.appendChild(el)});$$('.kpi-slider').forEach(sl=>sl.addEventListener('input',e=>{const k=state.kpis.find(x=>x.id==e.target.dataset.id);k.progress=+e.target.value;localStorage.setItem('gd-kpis',JSON.stringify(state.kpis));renderKpis()}));}
renderKpis();
function renderQuestions(){const c=$('#questionList');c.innerHTML='';questions.forEach((q,i)=>{const a=state.answers[i]||{};const card=document.createElement('article');card.className='panel question-card';card.innerHTML=`<div class="question-head"><div class="question-number">${i+1}</div><div><h2>${q.title}</h2><p>${q.text}</p></div></div><div class="question-body"><div class="scale">${[1,2,3,4,5].map(n=>`<button type="button" data-q="${i}" data-value="${n}" class="${a.score==n?'selected':''}">${n}</button>`).join('')}</div><div class="rubric" id="rubric-${i}">${a.score?q.rubrics[a.score]:'Selecciona una valoración para ver la descripción asociada.'}</div>${q.evidence?`<label class="field-label">Evidencia que respalda tu respuesta</label><textarea class="evidence" data-evidence="${i}" placeholder="Describe brevemente la evidencia...">${a.evidence||''}</textarea>`:''}</div>`;c.appendChild(card)});$$('.scale button').forEach(b=>b.addEventListener('click',()=>{const i=b.dataset.q;state.answers[i]=state.answers[i]||{};state.answers[i].score=+b.dataset.value;localStorage.setItem('gd-eval',JSON.stringify(state.answers));renderQuestions();updateEvalProgress()}));$$('[data-evidence]').forEach(t=>t.addEventListener('input',e=>{const i=e.target.dataset.evidence;state.answers[i]=state.answers[i]||{};state.answers[i].evidence=e.target.value;localStorage.setItem('gd-eval',JSON.stringify(state.answers))}));updateEvalProgress();}
function updateEvalProgress(){const done=questions.filter((_,i)=>state.answers[i]?.score).length;const pct=Math.round(done/questions.length*100);$('#evalPercent').textContent=pct+'%';$('#evalCounter').textContent=`${done} de ${questions.length} preguntas`;$('#evalBar').style.width=pct+'%';}
renderQuestions();$('#saveEval').addEventListener('click',()=>toast('Borrador guardado'));$('#submitEval').addEventListener('click',()=>{const done=questions.filter((_,i)=>state.answers[i]?.score).length;if(done<questions.length){toast('Completa todas las preguntas antes de enviar');return;}$('#evalStatus').textContent='Enviada';$('#evalStatus').className='status-pill success';toast('Evaluación enviada al jefe')});
function openModal(title,html){$('#modalTitle').textContent=title;$('#modalBody').innerHTML=`<div class="modal-body">${html}</div>`;$('#modal').classList.add('open');$('#modal').setAttribute('aria-hidden','false')}
function closeModal(){$('#modal').classList.remove('open');$('#modal').setAttribute('aria-hidden','true')}$('#closeModal').addEventListener('click',closeModal);$('#modal').addEventListener('click',e=>{if(e.target===$('#modal'))closeModal()});
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)}
$('#addKpiBtn').addEventListener('click',()=>openModal('Agregar objetivo / KPI',`<div class="form-grid"><label class="wide">Objetivo<input id="mGoal" class="control" placeholder="Describe el objetivo"></label><label>Indicador<input id="mIndicator" class="control" placeholder="Indicador"></label><label>Meta<input id="mMeta" class="control" placeholder="Meta"></label><label>Línea base<input id="mBase" class="control" placeholder="Línea base"></label><label>Avance inicial (%)<input id="mProgress" class="control" type="number" min="0" max="100" value="0"></label></div><div class="modal-actions"><button class="btn secondary" onclick="document.querySelector('#modal').classList.remove('open')">Cancelar</button><button id="saveKpiModal" class="btn primary">Guardar</button></div>`));
document.addEventListener('click',e=>{if(e.target?.id==='saveKpiModal'){state.kpis.push({id:Date.now(),title:$('#mGoal').value||'Nuevo objetivo',indicator:$('#mIndicator').value||'Por definir',meta:$('#mMeta').value||'Por definir',base:$('#mBase').value||'Por definir',progress:+$('#mProgress').value||0});localStorage.setItem('gd-kpis',JSON.stringify(state.kpis));renderKpis();closeModal();toast('Objetivo agregado')}});
function sessionModal(){openModal('Registrar reunión',`<div class="form-grid"><label>Tipo de sesión<select class="control"><option>Sesión de arranque</option><option>Check-in 1</option><option>Check-in 2</option></select></label><label>Fecha<input class="control" type="date"></label><label class="wide">Avances<textarea class="control" placeholder="Principales avances..."></textarea></label><label class="wide">Obstáculos / ajustes<textarea class="control" placeholder="Obstáculos identificados..."></textarea></label><label class="wide">Acuerdos y próximos pasos<textarea class="control" placeholder="Acuerdos concretos..."></textarea></label></div><div class="modal-actions"><button class="btn secondary" id="cancelSession">Cancelar</button><button class="btn primary" id="saveSession">Guardar acta</button></div>`)}
$('#newSessionBtn').addEventListener('click',sessionModal);$('#registerCheckin').addEventListener('click',sessionModal);document.addEventListener('click',e=>{if(e.target?.id==='cancelSession')closeModal();if(e.target?.id==='saveSession'){closeModal();toast('Acta de reunión registrada')}});
$$('[data-admin-tab]').forEach(b=>b.addEventListener('click',()=>{$$('[data-admin-tab]').forEach(x=>x.classList.toggle('active',x===b));$$('.admin-pane').forEach(x=>x.classList.toggle('active',x.id===b.dataset.adminTab))}));
$('#addExceptionBtn').addEventListener('click',()=>openModal('Nueva excepción de estructura',`<div class="form-grid"><label>Persona<input id="exPerson" class="control" placeholder="Buscar persona"></label><label>Jefe oficial<input id="exOfficial" class="control" placeholder="Jefe oficial"></label><label>Evaluador excepcional<input id="exNew" class="control" placeholder="Nuevo evaluador"></label><label>Vigencia<select id="exPeriod" class="control"><option>S1 2027</option><option>S2 2027</option><option>Todo el ciclo 2027</option></select></label><label class="wide">Motivo<textarea id="exReason" class="control" placeholder="Describe la razón de la excepción"></textarea></label></div><div class="modal-actions"><button class="btn secondary" id="cancelEx">Cancelar</button><button class="btn primary" id="saveEx">Guardar excepción</button></div>`));
document.addEventListener('click',e=>{if(e.target?.id==='cancelEx')closeModal();if(e.target?.id==='saveEx'){const row=document.createElement('tr');row.innerHTML=`<td>${$('#exPerson').value||'Persona'}</td><td>${$('#exOfficial').value||'-'}</td><td>${$('#exNew').value||'-'}</td><td>${$('#exReason').value||'Excepción manual'}</td><td>${$('#exPeriod').value}</td><td><button class="link-btn">Editar</button></td>`;$('#exceptionRows').appendChild(row);closeModal();toast('Excepción agregada')}});
$('#validateMatrix').addEventListener('click',()=>toast('Validación completada: 2 observaciones requieren revisión'));
$$('.openAction').forEach(b=>b.addEventListener('click',()=>openModal('Plan de acción del Comité',`<div class="form-grid"><label>Tipo de decisión<select class="control"><option>Plan de desarrollo</option><option>Reconocimiento</option><option>Seguimiento cercano</option><option>Otra acción</option></select></label><label>Fecha objetivo<input class="control" type="date"></label><label class="wide">Acción / decisión<textarea class="control" placeholder="Describe el plan de acción aprobado por el Comité..."></textarea></label></div><div class="modal-actions"><button class="btn secondary" id="cancelAction">Cancelar</button><button class="btn primary" id="saveAction">Guardar y notificar</button></div>`)));
document.addEventListener('click',e=>{if(e.target?.id==='cancelAction')closeModal();if(e.target?.id==='saveAction'){closeModal();toast('Plan guardado. Queda listo para notificar al colaborador')}});
